### ISSUE TITLE
GUI runtime panic caused by window size

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#88]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/chainbase-labs/manuscript-core/discussions).
- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Environment

```
📜 Manuscript Core:
  Version:	1.1.0

🏗️  Build Information:
  Go Version:	go1.22.5
  Rust Version:	1.83.0
  Git Commit:	1727168
  Built:	2024-12-11:16:18:33

💻 System Information:
  Unix Name:	Linux fedora-workstation 6.11.10-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 23 00:51:20 UTC 2024 x86_64 GNU/Linux
  OS/Arch:	linux/amd64

🐳 Docker Environment:
  Docker:	'27.3.1'
  Docker Desktop:	'4.36.0'
```

### Steps to reproduce

1. build `manuscript-gui`
2. make terminal window small

**OR** 

1. make terminal window small
2. build `manuscript-gui`

### ✔️ Expected Behavior

Successful GUI Launch :rocket: 
![image](https://github.com/user-attachments/assets/96adab21-2147-4976-9b51-9f8ea5a1054e)

### ❌ Actual Behavior

When running the `manuscript-gui` command with small terminal:

```
thread 'main' panicked at /home/kagemnikarimu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.29.0/src/buffer/buffer.rs:253:13:
index outside of buffer: the area is Rect { x: 0, y: 0, width: 80, height: 24 } but index is (65529, 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When making the terminal small after running the `manuscript-gui` command:

```
thread 'main' panicked at alloc/src/slice.rs:565:50:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by KagemniKarimu** [comment]
Thank you @youngpriince for the awesome work! :tada:

**Comment by KagemniKarimu** [comment]
@youngpriince  Reopening the issue.
I ran into the issue again after building from source on this week's community code :(

```
log_file_path: /home/kagemnikarimu/.manuscript/logs/manuscript_2024-12-18.log
thread 'main' panicked at /home/kagemnikarimu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-core-0.1.0-alpha.0/src/buffer/buffer.rs:253:13:
index outside of buffer: the area is Rect { x: 0, y: 0, width: 80, height: 24 } but index is (65529, 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

log file at log file path is empty; full `RUST_BACKTRACE` below:

```
└──> RUST_BACKTRACE=full manuscript-gui
log_file_path: /home/kagemnikarimu/.manuscript/logs/manuscript_2024-12-18.log
thread 'main' panicked at /home/kagemnikarimu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-core-0.1.0-alpha.0/src/buffer/buffer.rs:253:13:
index outside of buffer: the area is Rect { x: 0, y: 0, width: 80, height: 24 } but index is (65529, 1)
stack backtrace:
   0:     0x55c37a8772ca - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hddb63c9699c7309a
   1:     0x55c37a8a3d83 - core::fmt::write::hc338d61058c0d66c
   2:     0x55c37a872aa3 - std::io::Write::write_fmt::h80dab97476750852
   3:     0x55c37a877112 - std::sys::backtrace::BacktraceLock::print::h8f82e207cdd02441
   4:     0x55c37a87860a - std::panicking::default_hook::{{closure}}::hced8387e9fe5d421
   5:     0x55c37a878450 - std::panicking::default_hook::ha3f6ad90792a97b6
   6:     0x55c37a878ca8 - std::panicking::rust_panic_with_hook::h061c0c1eebc4ec34
   7:     0x55c37a878a6a - std::panicking::begin_panic_handler::{{closure}}::h5e30b0d14d1187f1
   8:     0x55c37a8777a9 - std::sys::backtrace::__rust_end_short_backtrace::h5df085eb7f7be6aa
   9:     0x55c37a8786fc - rust_begin_unwind
  10:     0x55c37a4f1fa0 - core::panicking::panic_fmt::h70cef1aa03d57ac6
  11:     0x55c37a773622 - ratatui_core::buffer::buffer::Buffer::index_of::{{closure}}::h59aee45b374bec56
  12:     0x55c37a773598 - ratatui_core::buffer::buffer::Buffer::index_of::h9401a1b80079d7af
  13:     0x55c37a76925e - <&ratatui_widgets::paragraph::Paragraph as ratatui_core::widgets::widget::Widget>::render::hcd3c7f420bfa540c
  14:     0x55c37a768ffd - <ratatui_widgets::paragraph::Paragraph as ratatui_core::widgets::widget::Widget>::render::h1a2328fd261e17c6
  15:     0x55c37a5780a1 - manuscript_gui::ui::draw::hc41d674a1e4a3e60
  16:     0x55c37a5743b8 - ratatui::terminal::terminal::Terminal<B>::try_draw::h1f98878e4b7c238b
  17:     0x55c37a54075e - manuscript_gui::app::App::run::h9e903345c60ee570
  18:     0x55c37a511269 - tokio::runtime::park::CachedParkThread::block_on::heeee53651d820ccc
  19:     0x55c37a52192c - tokio::runtime::context::runtime::enter_runtime::h63c1f60f9b76ccfe
  20:     0x55c37a52cf1d - tokio::runtime::runtime::Runtime::block_on::h450890ee0cd59afe
  21:     0x55c37a52288a - manuscript_gui::main::h75645e861128985b
  22:     0x55c37a532133 - std::sys::backtrace::__rust_begin_short_backtrace::h7c5be7024bc57e83
  23:     0x55c37a51aba3 - std::rt::lang_start::{{closure}}::hc7fb70e3d4a508c7
  24:     0x55c37a86bdde - std::rt::lang_start_internal::h10052b6af5e10459
  25:     0x55c37a522965 - main
  26:     0x7fd8524fa248 - __libc_start_call_main
  27:     0x7fd8524fa30b - __libc_start_main_impl
  28:     0x55c37a4f27e5 - _start
  29:                0x0 - <unknown>
```

**Comment by youngpriince** [comment]
@KagemniKarimu I'll check it out now.

**Comment by youngpriince** [comment]
@KagemniKarimu Kindly check [#107](https://github.com/chainbase-labs/manuscript-core/pull/107)

The issue is with the minimum terminal size. Typically, the minimum size for many terminal applications is `80x24`. I set the minimum dimensions to `80x28` as a safety threshold.
